### ISSUE TITLE
Spec reviewer signoff

### ISSUE THREAD

**Issue by caridy** [caridy/intl-plural-rules-spec#10]
Part of the stage 2 → 3 requirements is signoff from the official spec reviewers.
- [x] Daniel Ehrenberg (@littledan)
- [x] Stefan Penner (@stefanpenner)

**Comment by littledan** [comment]
Sorry for this coming at the last minute, but a couple nit-picks from the spec:
- Semantics: The prototype for new language features should not be an instance, but merely a holder for methods. We did things like change `RegExp.prototype` to not be a RegExp, even working through a bit of compatibility pain that resulted, in ES2015. `Intl.PluralRules.prototype` should follow this pattern, and it might even be worth looking into giving that treatment to other Intl classes if it is web-compatible.
- Formatting: In https://rawgit.com/caridy/intl-plural-rules-spec/master/index.html#sec-properties-of-intl-pluralrules-instances , make a sub-heading for the internal slots
- Clarification: https://rawgit.com/caridy/intl-plural-rules-spec/master/index.html#sec-Intl.PluralRules-internal-slots says "The value of the [[AvailableLocales]] internal slot is implementation defined within the constraints described in ." Link missing?

Otherwise, seems good to me. Any thoughts @jungshik ?

**Comment by zbraniecki** [comment]
@caridy - i think you said you'd like to apply that feedback and do some other minor cleanups before January. Is that still a plan?

**Comment by caridy** [comment]
yes, working on it at the moment @zbraniecki

**Comment by littledan** [comment]
All of these issues have been addressed, and the proposal advanced to Stage 3.
